version: "3.8"
services:
  backend:
    restart: always
    image: "node:16-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/:/home/node/app
    ports:
      - 3000:3000
    networks:
      - mynet
    command: sh -c 'yarn install && yarn run start:dev'

  frontend:
    restart: always
    image: "node:16-alpine"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./frontend/:/home/node/app
    ports:
      - 8080:8080
    networks:
      - mynet
    command: sh -c 'npm install && npm run serve'

networks:
  mynet:
##  compodoc:
##    image: "node:17-alpine"
##    user: "node"
##    working_dir: /home/node/app
##    volumes:
##      - ./backend/:/home/node/app
##    ports:
##      - 8080:8080
##    command: "npx @compodoc/compodoc -p tsconfig.json -s"
