version: "3.8"
services:
  backend:
    restart: always
    image: 42-node
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.AH
    environment:
      - NODE_ENV=development   
    volumes:
      - ./backend/:/app
    ports:
      - 3000:3000
    networks:
      - mynet
    command: sh -c 'npm install && npm run start:dev'

  frontend:
    restart: always
    image: 42-node
    volumes:
      - ./frontend/:/app
    ports:
      - 8080:8080
    networks:
      - mynet
    command: sh -c 'npm install && npm run serve'

##  compodoc:
##    image: "node:17-alpine"
##    user: "node"
##    working_dir: /home/node/app
##    volumes:
##      - ./backend/:/home/node/app
##    ports:
##      - 8080:8080
##    command: "npx @compodoc/compodoc -p tsconfig.json -s"

networks:
  mynet:
